# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Gustavo Wilgenhoff
tagline:             'Cuento cosas de programación'
description:         'El sitio está en construcción. Disculpe las molestias.'
url:                 https://wilgustavo.github.io
baseurl:             ''
paginate:            5
gems:                [jekyll-paginate]

# About/contact
author:
  name:              Gustavo Wilgenhoff
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             Beta-0.9.91

plugins:
  - jekyll-seo-tag
